[package]
name = "smt"
version = "0.1.0"
authors = ["YanOctavian"]
edition = "2021"

[dependencies]
ink = { version = "5.0.0", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = [
	"derive",
] }
smt-primitives = { path = "../../primitives",  default-features = false}

[dev-dependencies]
ink_e2e = { version = "5.0.0" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale-info/std",
    "smt-primitives/std",
]
ink-as-dependency = []
e2e-tests = []
